### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by vitorvas** [seamplex/milonga#1]
Erros trying to install milonga. Autogen complains as shown below. Something wrong with the new github repository? I was never good friend of m4...

`[vitors@heisenberg ~]$ cd bin/`
`[vitors@heisenberg bin]$ ls`
`[vitors@heisenberg bin]$ c`
`[vitors@heisenberg bin]$ git clone https://github.com/seamplex/milonga.git`
`Cloning into 'milonga'...`
`remote: Enumerating objects: 521, done.`
`remote: Counting objects: 100% (521/521), done.`
`remote: Compressing objects: 100% (219/219), done.`
`remote: Total 521 (delta 300), reused 515 (delta 294), pack-reused 0`
`Receiving objects: 100% (521/521), 6.58 MiB | 1.31 MiB/s, done.`
`Resolving deltas: 100% (300/300), done.`
`[vitors@heisenberg bin]$ cd milonga/`
`[vitors@heisenberg milonga]$ ./autogen.sh` 
`autogen: cleaning... ok`
`autogen: updating wasora, cloning... Cloning into 'wasora'...`
`remote: Enumerating objects: 2499, done.`
`remote: Counting objects: 100% (2499/2499), done.`
`remote: Compressing objects: 100% (881/881), done.`
`remote: Total 2499 (delta 1666), reused 2404 (delta 1571), pack-reused 0`
`Receiving objects: 100% (2499/2499), 5.11 MiB | 1.24 MiB/s, done.`
`Resolving deltas: 100% (1666/1666), done.`
`ok`
`autogen: checking out... ok`
`autogen: bootstrapping... fatal: No names found, cannot describe anything.`
`which: no pandoc in (/usr/lib64/openmpi/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/vitors/.local/bin:/home/vitors/bin)`
`ok`
`autogen: building makefile.am... building src/Makefile.am... ok`
`autogen: autoreconfiguring... configure.ac:17: error: AC_INIT should be called with package and version arguments`
`/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...`
`wasora/m4/wasora.m4:5: WASORA_PLUGIN_INIT_C is expanded from...`
`configure.ac:17: the top level`
`autom4te: /usr/bin/m4 failed with exit status: 1`
`aclocal: error: echo failed with exit status: 1`
`autoreconf: aclocal failed with exit status: 1`
`ok`
`[vitors@heisenberg milonga]$ `

Some information that might be useful:

`[vitors@heisenberg milonga]$ uname -a`
`Linux heisenberg 5.3.7-200.fc30.x86_64 #1 SMP Fri Oct 18 20:13:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
`[vitors@heisenberg milonga]$ env | grep PETS`
`PETSC_DIR=/home/vitors/lib/petsc-3.12.1`
`PETSC_ARCH=arch-linux2-c-debug`
`[vitors@heisenberg milonga]$ env | grep SLEP`
`SLEPC_DIR=/home/vitors/lib/slepc-3.12.1`
`[vitors@heisenberg milonga]$ gcc --version`
`gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)`
`Copyright (C) 2019 Free Software Foundation, Inc.`
`This is free software; see the source for copying conditions.  There is NO`
`warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by gtheler** [comment]
Sorry, I forgot to push the tags which `git describe` needs.

Can you check now please?

**Comment by vitorvas** [comment]
No need to be sorry. We're here to help you detect these little issues.
Working perfectly now, thanks!

`[vitors@heisenberg milonga]$ ./milonga` 
`milonga v0.6.6-ga69d882+Δ `
`free nuclear reactor core analysis code`
`[vitors@heisenberg milonga]$ `
